export enum Difficulty {
  EASY = "EASY",
  MEDIUM = "MEDIUM",
  HARD = "HARD"
}

export enum AttemptStatus {
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  ABANDONED = "ABANDONED"
}

export enum SubmissionStatus {
  DRAFT = "DRAFT",
  SUBMITTED = "SUBMITTED",
  EVALUATING = "EVALUATING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED"
}

export enum RubricDimension {
  REQUIREMENT_UNDERSTANDING = "REQUIREMENT_UNDERSTANDING",
  CLASS_RESPONSIBILITY = "CLASS_RESPONSIBILITY",
  COUPLING_COHESION = "COUPLING_COHESION",
  EXTENSIBILITY_PATTERNS = "EXTENSIBILITY_PATTERNS",
  EDGE_CASES_TESTABILITY = "EDGE_CASES_TESTABILITY"
}

export enum PayloadType {
  STRUCTURED_SPEC = "STRUCTURED_SPEC",
  DIAGRAM = "DIAGRAM",
  CODE = "CODE"
}
